networks:
    app-network:

services:                            
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        ports:
            - 8000:80
        volumes:
            - .:/app  
        networks:
            - app-network    
        extra_hosts:
            - host.docker.internal:host-gateway    
        depends_on:
            - php_fpm       
    php_fpm:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        tty: true
        volumes:
            - .:/app
        working_dir: /app
        environment:
            - PHP_IDE_CONFIG=serverName=server.loc
            - XDEBUG_MODES=develop,debug
            - REMOTE_HOST=host.docker.internal
            - REMOTE_PORT=9003
            - IDE_KEY=docker
        extra_hosts:
            - host.docker.internal:host-gateway
        networks:
            - app-network   
        restart: always